// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type CodeRun struct {
	ID         int64     `json:"id"`
	SessionID  string    `json:"session_id"`
	LessonPath string    `json:"lesson_path"`
	Section    string    `json:"section"`
	DurationMs int64     `json:"duration_ms"`
	Success    int64     `json:"success"`
	RanAt      time.Time `json:"ran_at"`
}

type EditorState struct {
	LessonPath string    `json:"lesson_path"`
	Content    string    `json:"content"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type HintReveal struct {
	ID         int64     `json:"id"`
	SessionID  string    `json:"session_id"`
	LessonPath string    `json:"lesson_path"`
	Section    string    `json:"section"`
	HintIndex  int64     `json:"hint_index"`
	RevealedAt time.Time `json:"revealed_at"`
}

type LessonOpen struct {
	ID         int64     `json:"id"`
	SessionID  string    `json:"session_id"`
	LessonPath string    `json:"lesson_path"`
	Section    string    `json:"section"`
	OpenedAt   time.Time `json:"opened_at"`
}

type Session struct {
	ID         string    `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

type SolutionReveal struct {
	ID         int64     `json:"id"`
	SessionID  string    `json:"session_id"`
	LessonPath string    `json:"lesson_path"`
	Section    string    `json:"section"`
	RevealedAt time.Time `json:"revealed_at"`
}

type TimeSpent struct {
	ID         int64     `json:"id"`
	SessionID  string    `json:"session_id"`
	LessonPath string    `json:"lesson_path"`
	Section    string    `json:"section"`
	Seconds    int64     `json:"seconds"`
	RecordedAt time.Time `json:"recorded_at"`
}
