// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const ensureSession = `-- name: EnsureSession :exec
INSERT INTO sessions (id) VALUES (?)
ON CONFLICT(id) DO UPDATE SET last_seen_at = CURRENT_TIMESTAMP
`

func (q *Queries) EnsureSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, ensureSession, id)
	return err
}

const getEditorState = `-- name: GetEditorState :one
SELECT content FROM editor_state WHERE lesson_path = ?
`

func (q *Queries) GetEditorState(ctx context.Context, lessonPath string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEditorState, lessonPath)
	var content string
	err := row.Scan(&content)
	return content, err
}

const hintsPerLesson = `-- name: HintsPerLesson :many
SELECT lesson_path, section, COUNT(*) AS reveals
FROM hint_reveals
GROUP BY lesson_path, section
ORDER BY reveals DESC
`

type HintsPerLessonRow struct {
	LessonPath string `json:"lesson_path"`
	Section    string `json:"section"`
	Reveals    int64  `json:"reveals"`
}

func (q *Queries) HintsPerLesson(ctx context.Context) ([]HintsPerLessonRow, error) {
	rows, err := q.db.QueryContext(ctx, hintsPerLesson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HintsPerLessonRow{}
	for rows.Next() {
		var i HintsPerLessonRow
		if err := rows.Scan(&i.LessonPath, &i.Section, &i.Reveals); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lessonTotals = `-- name: LessonTotals :many
SELECT
    lesson_path,
    section,
    (SELECT COUNT(*) FROM lesson_opens o WHERE o.lesson_path = l.lesson_path) AS opens,
    (SELECT COALESCE(SUM(seconds), 0) FROM time_spent t WHERE t.lesson_path = l.lesson_path) AS total_seconds,
    (SELECT COUNT(*) FROM hint_reveals h WHERE h.lesson_path = l.lesson_path) AS hint_reveals,
    (SELECT COUNT(*) FROM solution_reveals r WHERE r.lesson_path = l.lesson_path) AS solution_reveals,
    (SELECT COUNT(*) FROM code_runs c WHERE c.lesson_path = l.lesson_path) AS code_runs
FROM (
    SELECT DISTINCT lesson_path, section FROM lesson_opens
    UNION SELECT DISTINCT lesson_path, section FROM time_spent
    UNION SELECT DISTINCT lesson_path, section FROM code_runs
    UNION SELECT DISTINCT lesson_path, section FROM hint_reveals
    UNION SELECT DISTINCT lesson_path, section FROM solution_reveals
) l
ORDER BY total_seconds DESC
`

type LessonTotalsRow struct {
	LessonPath      string      `json:"lesson_path"`
	Section         string      `json:"section"`
	Opens           int64       `json:"opens"`
	TotalSeconds    interface{} `json:"total_seconds"`
	HintReveals     int64       `json:"hint_reveals"`
	SolutionReveals int64       `json:"solution_reveals"`
	CodeRuns        int64       `json:"code_runs"`
}

func (q *Queries) LessonTotals(ctx context.Context) ([]LessonTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, lessonTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonTotalsRow{}
	for rows.Next() {
		var i LessonTotalsRow
		if err := rows.Scan(
			&i.LessonPath,
			&i.Section,
			&i.Opens,
			&i.TotalSeconds,
			&i.HintReveals,
			&i.SolutionReveals,
			&i.CodeRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overallStats = `-- name: OverallStats :one
SELECT
    (SELECT COUNT(*) FROM sessions) AS sessions,
    (SELECT COUNT(*) FROM lesson_opens) AS opens,
    (SELECT COALESCE(SUM(seconds), 0) FROM time_spent) AS total_seconds,
    (SELECT COUNT(*) FROM hint_reveals) AS hint_reveals,
    (SELECT COUNT(*) FROM solution_reveals) AS solution_reveals,
    (SELECT COUNT(*) FROM code_runs) AS code_runs,
    (SELECT COUNT(*) FROM code_runs WHERE success = 1) AS successful_runs
`

type OverallStatsRow struct {
	Sessions        int64       `json:"sessions"`
	Opens           int64       `json:"opens"`
	TotalSeconds    interface{} `json:"total_seconds"`
	HintReveals     int64       `json:"hint_reveals"`
	SolutionReveals int64       `json:"solution_reveals"`
	CodeRuns        int64       `json:"code_runs"`
	SuccessfulRuns  int64       `json:"successful_runs"`
}

func (q *Queries) OverallStats(ctx context.Context) (OverallStatsRow, error) {
	row := q.db.QueryRowContext(ctx, overallStats)
	var i OverallStatsRow
	err := row.Scan(
		&i.Sessions,
		&i.Opens,
		&i.TotalSeconds,
		&i.HintReveals,
		&i.SolutionReveals,
		&i.CodeRuns,
		&i.SuccessfulRuns,
	)
	return i, err
}

const recordCodeRun = `-- name: RecordCodeRun :exec
INSERT INTO code_runs (session_id, lesson_path, section, duration_ms, success)
VALUES (?, ?, ?, ?, ?)
`

type RecordCodeRunParams struct {
	SessionID  string `json:"session_id"`
	LessonPath string `json:"lesson_path"`
	Section    string `json:"section"`
	DurationMs int64  `json:"duration_ms"`
	Success    int64  `json:"success"`
}

func (q *Queries) RecordCodeRun(ctx context.Context, arg RecordCodeRunParams) error {
	_, err := q.db.ExecContext(ctx, recordCodeRun,
		arg.SessionID,
		arg.LessonPath,
		arg.Section,
		arg.DurationMs,
		arg.Success,
	)
	return err
}

const recordHintReveal = `-- name: RecordHintReveal :exec
INSERT INTO hint_reveals (session_id, lesson_path, section, hint_index) VALUES (?, ?, ?, ?)
`

type RecordHintRevealParams struct {
	SessionID  string `json:"session_id"`
	LessonPath string `json:"lesson_path"`
	Section    string `json:"section"`
	HintIndex  int64  `json:"hint_index"`
}

func (q *Queries) RecordHintReveal(ctx context.Context, arg RecordHintRevealParams) error {
	_, err := q.db.ExecContext(ctx, recordHintReveal,
		arg.SessionID,
		arg.LessonPath,
		arg.Section,
		arg.HintIndex,
	)
	return err
}

const recordOpen = `-- name: RecordOpen :exec
INSERT INTO lesson_opens (session_id, lesson_path, section) VALUES (?, ?, ?)
`

type RecordOpenParams struct {
	SessionID  string `json:"session_id"`
	LessonPath string `json:"lesson_path"`
	Section    string `json:"section"`
}

func (q *Queries) RecordOpen(ctx context.Context, arg RecordOpenParams) error {
	_, err := q.db.ExecContext(ctx, recordOpen, arg.SessionID, arg.LessonPath, arg.Section)
	return err
}

const recordSolutionReveal = `-- name: RecordSolutionReveal :exec
INSERT INTO solution_reveals (session_id, lesson_path, section) VALUES (?, ?, ?)
`

type RecordSolutionRevealParams struct {
	SessionID  string `json:"session_id"`
	LessonPath string `json:"lesson_path"`
	Section    string `json:"section"`
}

func (q *Queries) RecordSolutionReveal(ctx context.Context, arg RecordSolutionRevealParams) error {
	_, err := q.db.ExecContext(ctx, recordSolutionReveal, arg.SessionID, arg.LessonPath, arg.Section)
	return err
}

const recordTimeSpent = `-- name: RecordTimeSpent :exec
INSERT INTO time_spent (session_id, lesson_path, section, seconds) VALUES (?, ?, ?, ?)
`

type RecordTimeSpentParams struct {
	SessionID  string `json:"session_id"`
	LessonPath string `json:"lesson_path"`
	Section    string `json:"section"`
	Seconds    int64  `json:"seconds"`
}

func (q *Queries) RecordTimeSpent(ctx context.Context, arg RecordTimeSpentParams) error {
	_, err := q.db.ExecContext(ctx, recordTimeSpent,
		arg.SessionID,
		arg.LessonPath,
		arg.Section,
		arg.Seconds,
	)
	return err
}

const sectionTotals = `-- name: SectionTotals :many
SELECT
    section,
    (SELECT COUNT(*) FROM lesson_opens o WHERE o.section = s.section) AS opens,
    (SELECT COALESCE(SUM(seconds), 0) FROM time_spent t WHERE t.section = s.section) AS total_seconds,
    (SELECT COUNT(*) FROM hint_reveals h WHERE h.section = s.section) AS hint_reveals,
    (SELECT COUNT(*) FROM solution_reveals r WHERE r.section = s.section) AS solution_reveals,
    (SELECT COUNT(*) FROM code_runs c WHERE c.section = s.section) AS code_runs
FROM (
    SELECT DISTINCT section FROM lesson_opens
    UNION SELECT DISTINCT section FROM time_spent
    UNION SELECT DISTINCT section FROM code_runs
    UNION SELECT DISTINCT section FROM hint_reveals
    UNION SELECT DISTINCT section FROM solution_reveals
) s
ORDER BY total_seconds DESC
`

type SectionTotalsRow struct {
	Section         string      `json:"section"`
	Opens           int64       `json:"opens"`
	TotalSeconds    interface{} `json:"total_seconds"`
	HintReveals     int64       `json:"hint_reveals"`
	SolutionReveals int64       `json:"solution_reveals"`
	CodeRuns        int64       `json:"code_runs"`
}

func (q *Queries) SectionTotals(ctx context.Context) ([]SectionTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, sectionTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SectionTotalsRow{}
	for rows.Next() {
		var i SectionTotalsRow
		if err := rows.Scan(
			&i.Section,
			&i.Opens,
			&i.TotalSeconds,
			&i.HintReveals,
			&i.SolutionReveals,
			&i.CodeRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEditorState = `-- name: UpsertEditorState :exec
INSERT INTO editor_state (lesson_path, content, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(lesson_path) DO UPDATE SET content = excluded.content, updated_at = CURRENT_TIMESTAMP
`

type UpsertEditorStateParams struct {
	LessonPath string `json:"lesson_path"`
	Content    string `json:"content"`
}

func (q *Queries) UpsertEditorState(ctx context.Context, arg UpsertEditorStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertEditorState, arg.LessonPath, arg.Content)
	return err
}
